### ISSUE TITLE
Widget: dynamic templating

### ISSUE THREAD

**Issue by kickinbahk** [BuildFire/sdk#183] opened 2016-01-25 23:27 UTC
The following is from a customer trying to build his own plugin: 

I am asking for some assistance as I am trying to create a customize plugin where users can edit info on the widget page.

What I need to have is displayed in the following. Let’s say a table is displayed with some info that the user wants to edit. This is the widget image below: (there should be some info in the cell on the left of the edit button)
![1](https://cloud.githubusercontent.com/assets/10123801/12568074/f49a1804-c377-11e5-8daf-62dc005f72d3.png)

When the user clicks on the Edit button, an input box should be displayed where the info can be edited. At the same time, the Edit button becomes a Save button to save the info. On the below image, as you can see, the input bow is not created.
![2](https://cloud.githubusercontent.com/assets/10123801/12568079/fd99b072-c377-11e5-9a34-6badb115d094.png)

This is actually my issue: I cannot get the input box to appear. I created a directive that generates a dynamic template according to the context. But I cannot get it work. This is the code for the directive:
![3](https://cloud.githubusercontent.com/assets/10123801/12568082/0b75fd0e-c378-11e5-9590-e935a5abdb30.png)

I also join the index.html of the widget (I do not do  any change on the controller). I included this page on whatever plugin (I used a Textplugin) since I open the emulator loading this specific page, I do not load the index.html of the plugintester. I do that as I had some issue with the plugintester (that will be in a following question).

Let me know if something is unclear.

**Comment by dams57k** [comment] 2016-01-26 00:56
Hello,

Here is an add-on to the previous comment.

I need to implement a User Interface where the user can edit his/her info on the widget directly, and do not really know how to proceed within buildfire. I have assumed that the info edition must be done on the same page, i.e., once the user saves the data, there is not redirection to another page where the data are displayed. If there were 2 different pages, one for edition (with forms that the user fills), and one that displays the user info as a static HTML page, things would be easier. But right now, I assume that it is possible to have only one page.

Here are my additional question

1.Am I right making this assumption, or is there a way I can define 2 views within the same plugin, index.html and another.html ? In the case 2 views can be present, I would have to do redirections using HTML links (<a></a>), as I do not have access to $routeProvider, do I ?


Thank you,

Damien

**Comment by sakshityagi** [comment] 2016-01-29 17:17
Hi Damien,

I had a look at the issues you are facing, please refer to the below answers.

* Firstly, you want to create a user information form in widget section, where user can click on some "edit" button and information become editable. I would like to mention that currently, widget section is `readonly` for `Datastore` for data security reasons, that might change in near future. But for now you cannot make user save data in widget side using Datastore. But there can be some other options to save the data maybe local storage or using mailto.  

* Secondly, the issue that you have mentioned there is you want to have more that one view in widget section , so that if user clicks on edit, it can open another view and show information to edit. We have already implemented multiple view routing in some of our plugins. You can refer them here : https://github.com/BuildFire/youtubePlugin  and https://github.com/Buildfire/eventsManualPlugin .

What we have done in these plugins is we have created home view in index.html that is the main view and in your case it should be the user form with some information. Now if user click on edit button, another view is opened just above the home view. We have used `ng-view` for that. Sample html for it :

```
<body>
 <div class="content">
   <div ng-controller="WidgetHomeCtrl as WidgetHome">
     <form>

     </form>
   </div>
 </div>
 <div ng-view="" class="content" ng-hide="showFeed">
 </div>
</body>

```
Here when the plugin is loaded the form is shown and scope variable "showFeed" is set to false. When user click on edit button, we make "showFeed" true and the ng-view is loaded which is the editable form.

Routing in app.js for this :

```
$routeProvider
        .when('/', {
          template: '<div></div>'
        })
        .when('/user/:id', {
          templateUrl: 'templates/user.html',
          controller: 'WidgetUserCtrl',
          controllerAs: 'WidgetUser'
        })
        .otherwise('/');
```

Hope this will be of some help. Please let me know in case you need more info on this.

**Comment by dams57k** [comment] 2016-02-02 20:39
Hi Sakshi,

Thank you for your answer, it is very helpful to me! It made me realize
that it is possible to create an internal routing system to a plugin,
coding it in app.js.

I have another related question in my try to create a user information form
in the widget section. I would like to come up with something that looks
like this:

[image: Inline image 1]

Thus, I included the user info form in the GridLayoutLauncher plugin, and
take advantage of the fact that it allows you to load other plugins. I was
able to place the icons the way I want to. The first icon I want to place
is the Edit button. I was able to do that as well, and hoped that including
the ng-click attribute in the template, it would call a function that
changes the view. But that is not the case, i.e clicking on the Edit button
does not change anything. This is the code portion, in prepareSlidesHTML
function of Gridlayout/widget/index.html.

[image: Inline image 2]

I am aware that the code should “compile” the angularJS commands, I think
in this case it is “link” since the context is changing. I though this
function does it:

[image: Inline image 3]

But that does not fixed my issue. By the way, what is the purpose of this
above function then?

Thank you for your help!

Damien

**Comment by sakshityagi** [comment] 2016-02-03 04:46
@dams57k Hey can you please re-attach the images in above comment, so that I can have more context of the issue . 

Thank you.

**Comment by dams57k** [comment] 2016-02-03 19:17
Sure, here you go:
Thanks


[image: Inline image 4]
[image: Inline image 2]


[image: Inline image 3]

**Comment by RJASeoud** [comment] 2016-02-04 02:14
Greetings @dams57k  Thanks for your response.
Unfortunately we are only seeing the following:

[image: Inline image 4]
[image: Inline image 2]


[image: Inline image 3]


Without any images. I'm not sure if its an attachment issue?

Thanks,
RJ

**Comment by dams57k** [comment] 2016-02-04 17:46
Hi RJ,

Thanks for letting know and sorry about that. It must be due to the set up
of our firewalls.
I am sending them from another source. Can you get the image now ?

Thanks,
Damien

---------- Forwarded message ----------
From: damsk <dams57k@gmail.com>
Date: Wed, Feb 3, 2016 at 11:17 AM
Subject: Re: [sdk] Widget: dynamic templating (#183)
To: BuildFire/sdk <
reply@reply.github.com
>



Sure, here you go:
Thanks


[image: Inline image 4]
[image: Inline image 2]


[image: Inline image 3]

**Comment by RJASeoud** [comment] 2016-02-04 19:05
Greetings @dams57k  

Unfortunately still failing, can I suggest that we try zipping the images and attaching the ZIP file instead?

Thank you,
RJ

**Comment by dams57k** [comment] 2016-02-04 20:31
Hopefully that works :).
Damien

**Comment by dams57k** [comment] 2016-02-05 18:00
Hi RJ,

Did you get a chance to check if you got the images ?

Thanks,
Damien

**Comment by sakshityagi** [comment] 2016-02-08 11:30
@dams57k 

Hi Damien,
We are still not able to access the images. Is there any other medium where you can share them? You can also drop us an email with those images attached at our support emial id : `support@buildfire.com` with issue number and title in subject.

Thanks.

**Comment by dams57k** [comment] 2016-02-08 20:08
Hi Sakshi,

Ok, there is apparently an issue with size of format, so I am trying to
send you the .html and pdf of the image, which is way smaller is size, and
probably more efficient anyway…
I am resending the initial description of the issue, with the reference in
the index.html file I attached to this mail.
Thanks !
Damien


I would like to come up with something that looks like the image on
widget.pdf

Thus, I included the user info form in the GridLayoutLauncher plugin, and
take advantage of the fact that it allows you to load other plugins. I was
able to place the icons the way I want to. The first icon I want to place
is the Edit button. I was able to do that as well, and hoped that including
the ng-click attribute in the template, it would call a function that
changes the view. But that is not the case, i.e clicking on the Edit button
does not change anything. This is the code portion, in prepareSlidesHTML
function of Gridlayout/widget/index.html (line 608-613). I call the
function “user_switchEditState()” that is defined at line 275.



I am aware that the code should “compile” the angularJS commands, I think
in this case it is “link” since the context is changing. I though this
function does it (index.html line 650)

But that does not fixed my issue. By the way, what is the purpose of this
above function then?

Finally I noticed, that when I click twice on the “Edit” button in the
plugin, all the icons disappear, and the content/index.html cannot load the
plugins anymore. I get an error message saying that the loadAllPlugins
attribute of $scope.data is undefined. But I actually was cautious not to
modify anything in $scope.data.

Thank you for your help!

Damien

**Comment by dams57k** [comment] 2016-02-09 18:08
Hi Sakshi,

Were you able to get all the attached pieces ?

Thanks,
Damien

**Comment by sakshityagi** [comment] 2016-02-10 11:16
Hi Damien,
I tried looking for your email but couldn't find the images. Have you emailed them to `support@buildfire.com` ? Because your question refer to the images and for proper context, I need to see the attachments. 

Thanks.

**Comment by dams57k** [comment] 2016-02-10 17:35
Hi Sakshi,

I sent it to devsupport@buildfire.com. I only attached an .html and a .pdf
files. I am wondering if you can get any attachment through this mailbox.

Thanks,
Damien

**Comment by dams57k** [comment] 2016-02-10 23:40
I am trying to attach the pieces this way.
I checked in "Preview" that I can save them. 
The first one is the widget code I am working on.
The second is the image of what I would like to get.

Thanks,
Damien
[index.txt](https://github.com/BuildFire/sdk/files/125673/index.txt)

[widget.pdf](https://github.com/BuildFire/sdk/files/125663/widget.pdf)

**Comment by sakshityagi** [comment] 2016-02-11 07:14
Hi Damien,

I had a look at the `index.html` file you have attached. I see the problem why function `user_switchEditState()` is not working properly. It is because you have bind the click listener using **jquery**. So we need to **sync** it with **angular**. For that we have to do this `$scope.$apply()` at the end of this function. 

Thanks.

**Comment by dams57k** [comment] 2016-02-12 08:18
Hi Sakshi,

Thanks for your answer, clicking on the Edit button triggers the expected behavior. Now I want to insert the image uploading function that is present in the SocialPlugin, that somebody can use to post a picture. Right now I just want to copy and import what I need from the SocialPlugin to my plugin to get this function.
 
The option I consider is to have two angular modules within the same HTML page. From my research it looks like this is possible, provided the second module is manually bootstrapped to the HTML doc. I tried that (line  188 of the attached index.txt), but I still do not have the file windows that pops up when I click on the picture account. Can you tell me if that is actually ok to include a second angular module this way?

Thank you,
Damien  


[index.txt](https://github.com/BuildFire/sdk/files/127659/index.txt)

**Comment by DanielHindi** [comment] 2016-05-04 23:42
Closing for inactivity

**Closed by DanielHindi** 2016-05-04 23:42 UTC
